'0':
  build: .
  command: 'bash -c ''w'''
  working_dir: /app/user
  environment:
'1':
  build: .
  command: 'bash -c ''e'''
  working_dir: /app/user
  environment:
'2':
  build: .
  command: 'bash -c ''b'''
  working_dir: /app/user
  environment:
'3':
  build: .
  command: 'bash -c '' '''
  working_dir: /app/user
  environment:
'4':
  build: .
  command: 'bash -c ''j'''
  working_dir: /app/user
  environment:
'5':
  build: .
  command: 'bash -c ''a'''
  working_dir: /app/user
  environment:
'6':
  build: .
  command: 'bash -c ''v'''
  working_dir: /app/user
  environment:
'7':
  build: .
  command: 'bash -c ''a'''
  working_dir: /app/user
  environment:
'8':
  build: .
  command: 'bash -c '' '''
  working_dir: /app/user
  environment:
'9':
  build: .
  command: 'bash -c ''-'''
  working_dir: /app/user
  environment:
'10':
  build: .
  command: 'bash -c ''D'''
  working_dir: /app/user
  environment:
'11':
  build: .
  command: 'bash -c ''s'''
  working_dir: /app/user
  environment:
'12':
  build: .
  command: 'bash -c ''e'''
  working_dir: /app/user
  environment:
'13':
  build: .
  command: 'bash -c ''r'''
  working_dir: /app/user
  environment:
'14':
  build: .
  command: 'bash -c ''v'''
  working_dir: /app/user
  environment:
'15':
  build: .
  command: 'bash -c ''e'''
  working_dir: /app/user
  environment:
'16':
  build: .
  command: 'bash -c ''r'''
  working_dir: /app/user
  environment:
'17':
  build: .
  command: 'bash -c ''.'''
  working_dir: /app/user
  environment:
'18':
  build: .
  command: 'bash -c ''p'''
  working_dir: /app/user
  environment:
'19':
  build: .
  command: 'bash -c ''o'''
  working_dir: /app/user
  environment:
'20':
  build: .
  command: 'bash -c ''r'''
  working_dir: /app/user
  environment:
'21':
  build: .
  command: 'bash -c ''t'''
  working_dir: /app/user
  environment:
'22':
  build: .
  command: 'bash -c ''='''
  working_dir: /app/user
  environment:
'23':
  build: .
  command: 'bash -c ''$'''
  working_dir: /app/user
  environment:
'24':
  build: .
  command: 'bash -c ''P'''
  working_dir: /app/user
  environment:
'25':
  build: .
  command: 'bash -c ''O'''
  working_dir: /app/user
  environment:
'26':
  build: .
  command: 'bash -c ''R'''
  working_dir: /app/user
  environment:
'27':
  build: .
  command: 'bash -c ''T'''
  working_dir: /app/user
  environment:
'28':
  build: .
  command: 'bash -c '' '''
  working_dir: /app/user
  environment:
'29':
  build: .
  command: 'bash -c ''$'''
  working_dir: /app/user
  environment:
'30':
  build: .
  command: 'bash -c ''J'''
  working_dir: /app/user
  environment:
'31':
  build: .
  command: 'bash -c ''A'''
  working_dir: /app/user
  environment:
'32':
  build: .
  command: 'bash -c ''V'''
  working_dir: /app/user
  environment:
'33':
  build: .
  command: 'bash -c ''A'''
  working_dir: /app/user
  environment:
'34':
  build: .
  command: 'bash -c ''_'''
  working_dir: /app/user
  environment:
'35':
  build: .
  command: 'bash -c ''O'''
  working_dir: /app/user
  environment:
'36':
  build: .
  command: 'bash -c ''P'''
  working_dir: /app/user
  environment:
'37':
  build: .
  command: 'bash -c ''T'''
  working_dir: /app/user
  environment:
'38':
  build: .
  command: 'bash -c ''S'''
  working_dir: /app/user
  environment:
'39':
  build: .
  command: 'bash -c '' '''
  working_dir: /app/user
  environment:
'40':
  build: .
  command: 'bash -c ''-'''
  working_dir: /app/user
  environment:
'41':
  build: .
  command: 'bash -c ''j'''
  working_dir: /app/user
  environment:
'42':
  build: .
  command: 'bash -c ''a'''
  working_dir: /app/user
  environment:
'43':
  build: .
  command: 'bash -c ''r'''
  working_dir: /app/user
  environment:
'44':
  build: .
  command: 'bash -c '' '''
  working_dir: /app/user
  environment:
'45':
  build: .
  command: 'bash -c ''t'''
  working_dir: /app/user
  environment:
'46':
  build: .
  command: 'bash -c ''a'''
  working_dir: /app/user
  environment:
'47':
  build: .
  command: 'bash -c ''r'''
  working_dir: /app/user
  environment:
'48':
  build: .
  command: 'bash -c ''g'''
  working_dir: /app/user
  environment:
'49':
  build: .
  command: 'bash -c ''e'''
  working_dir: /app/user
  environment:
'50':
  build: .
  command: 'bash -c ''t'''
  working_dir: /app/user
  environment:
'51':
  build: .
  command: 'bash -c ''/'''
  working_dir: /app/user
  environment:
'52':
  build: .
  command: 'bash -c ''r'''
  working_dir: /app/user
  environment:
'53':
  build: .
  command: 'bash -c ''e'''
  working_dir: /app/user
  environment:
'54':
  build: .
  command: 'bash -c ''g'''
  working_dir: /app/user
  environment:
'55':
  build: .
  command: 'bash -c ''i'''
  working_dir: /app/user
  environment:
'56':
  build: .
  command: 'bash -c ''s'''
  working_dir: /app/user
  environment:
'57':
  build: .
  command: 'bash -c ''t'''
  working_dir: /app/user
  environment:
'58':
  build: .
  command: 'bash -c ''r'''
  working_dir: /app/user
  environment:
'59':
  build: .
  command: 'bash -c ''y'''
  working_dir: /app/user
  environment:
'60':
  build: .
  command: 'bash -c ''-'''
  working_dir: /app/user
  environment:
'61':
  build: .
  command: 'bash -c ''0'''
  working_dir: /app/user
  environment:
'62':
  build: .
  command: 'bash -c ''.'''
  working_dir: /app/user
  environment:
'63':
  build: .
  command: 'bash -c ''0'''
  working_dir: /app/user
  environment:
'64':
  build: .
  command: 'bash -c ''.'''
  working_dir: /app/user
  environment:
'65':
  build: .
  command: 'bash -c ''1'''
  working_dir: /app/user
  environment:
'66':
  build: .
  command: 'bash -c ''-'''
  working_dir: /app/user
  environment:
'67':
  build: .
  command: 'bash -c ''S'''
  working_dir: /app/user
  environment:
'68':
  build: .
  command: 'bash -c ''N'''
  working_dir: /app/user
  environment:
'69':
  build: .
  command: 'bash -c ''A'''
  working_dir: /app/user
  environment:
'70':
  build: .
  command: 'bash -c ''P'''
  working_dir: /app/user
  environment:
'71':
  build: .
  command: 'bash -c ''S'''
  working_dir: /app/user
  environment:
'72':
  build: .
  command: 'bash -c ''H'''
  working_dir: /app/user
  environment:
'73':
  build: .
  command: 'bash -c ''O'''
  working_dir: /app/user
  environment:
'74':
  build: .
  command: 'bash -c ''T'''
  working_dir: /app/user
  environment:
'75':
  build: .
  command: 'bash -c ''.'''
  working_dir: /app/user
  environment:
'76':
  build: .
  command: 'bash -c ''w'''
  working_dir: /app/user
  environment:
'77':
  build: .
  command: 'bash -c ''a'''
  working_dir: /app/user
  environment:
'78':
  build: .
  command: 'bash -c ''r'''
  working_dir: /app/user
  environment:
shell: null
